//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArtwork
    {
        public int kArtwork { get; set; }
        public Nullable<int> kLookClient { get; set; }
        public string vcClientID { get; set; }
        public string vcClientName { get; set; }
        public string vcArtworkDescription { get; set; }
        public string vcImageType { get; set; }
        public string fImage { get; set; }
        public Nullable<int> intImageWidth { get; set; }
        public Nullable<int> intImageHeight { get; set; }
        public Nullable<int> intFileSize { get; set; }
        public string vcFileName { get; set; }
        public string vcSource { get; set; }
    }
}
