//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCustomerArtwork
    {
        public int kCustomerArtwork { get; set; }
        public Nullable<int> kLookClient { get; set; }
        public string vcFileDescription { get; set; }
        public string vcFileName { get; set; }
        public string vcDropBoxURL { get; set; }
    }
}
