//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFabric
    {
        public int kFabric { get; set; }
        public Nullable<int> kLookClient { get; set; }
        public Nullable<int> kLookClientCustomer { get; set; }
        public Nullable<int> kFrame { get; set; }
        public string vcItemNumber { get; set; }
        public string vcSerialNumber { get; set; }
        public Nullable<int> intHeight { get; set; }
        public Nullable<int> intWidth { get; set; }
        public string vcExtrusion { get; set; }
        public string vcFileName { get; set; }
        public string vcNFCUrl { get; set; }
        public string vcLookCSR { get; set; }
        public Nullable<System.DateTime> dtShippedFromTLC { get; set; }
        public Nullable<System.DateTime> dtInstalled { get; set; }
        public string vcSource { get; set; }
        public string vcClientID { get; set; }
        public string vcClientName { get; set; }
        public string vcStatus { get; set; }
    }
}
