//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFrame
    {
        public int kFrame { get; set; }
        public Nullable<int> kLookClient { get; set; }
        public Nullable<int> kLookClientCustomer { get; set; }
        public Nullable<System.DateTime> dtShippedFromTLC { get; set; }
        public Nullable<System.DateTime> dtInstalled { get; set; }
        public string vcItemNumber { get; set; }
        public Nullable<int> intWidth { get; set; }
        public Nullable<int> intHeight { get; set; }
        public string vcFrame { get; set; }
        public string vcExtrusion { get; set; }
        public string vcFinish { get; set; }
        public string vcLighting { get; set; }
        public string vcMountingType { get; set; }
        public string vcSerialNumber { get; set; }
        public string vcFrameFileName { get; set; }
        public string vcInstalled { get; set; }
        public string vcLookCSR { get; set; }
        public string vcInStoreLocation { get; set; }
        public string vcSource { get; set; }
        public string vcClientID { get; set; }
        public string vcClientName { get; set; }
    }
}
