//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLookClient
    {
        public int kLookClient { get; set; }
        public string vcClientID { get; set; }
        public string vcClientName { get; set; }
        public string vcSource { get; set; }
    }
}
