//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLookClientCustomer
    {
        public int kLookClientCustomer { get; set; }
        public Nullable<int> kLookClient { get; set; }
        public string vcClientCustomerID { get; set; }
        public string vcClientCustomerName { get; set; }
        public string vcShipToName { get; set; }
        public string vcShipToAddress1 { get; set; }
        public string vcShipToAddress2 { get; set; }
        public string vcShipToAddress3 { get; set; }
        public string vcShipToAddress4 { get; set; }
        public string vcShipToCity { get; set; }
        public string vcShipToStateProvince { get; set; }
        public string vcShipToCountry { get; set; }
        public string vcShipToPostal { get; set; }
        public string vcShipToContact { get; set; }
        public string vcLookCSR { get; set; }
        public string vcSource { get; set; }
    }
}
