//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPromotionalMaterial
    {
        public int kPromotionalMaterial { get; set; }
        public string vcDescription { get; set; }
        public string vcFileName { get; set; }
        public string vcType { get; set; }
        public Nullable<int> intFileSize { get; set; }
        public string fFile { get; set; }
    }
}
