//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TlcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public int kUser { get; set; }
        public Nullable<int> kLookClient { get; set; }
        public bool bActive { get; set; }
        public Nullable<int> kUserLevel { get; set; }
        public string mUserProfile { get; set; }
        public string vcUserName { get; set; }
        public string vcFirstName { get; set; }
        public string vcLastName { get; set; }
        public bool bInstaller { get; set; }
        public string vcUserEmailAddress { get; set; }
        public string intCellPhoneNumber { get; set; }
        public string vcPosition { get; set; }
        public string vcPassword { get; set; }
        public string vcCustomer { get; set; }
    }
}
